### ISSUE TITLE
该方法需要手动指定每一层的prune ratio? 

### ISSUE THREAD

**Issue by PeiqinSun** [Eclipsess/CHIP_NeurIPS2021#1]
你好. 非常感谢你的工作. 有几个问题请教一下:
1. 如果是手动指定这个ratio, 那么在指定过程中有什么insight可以分享吗?
2. 请问有尝试过自动决定每层的ratio吗?

**Comment by Eclipsess** [comment]
1. 浅层保留比例多一些，深层保留比例少一些。
2. 目前没有尝试，ratio是按照HRank(CVPR2020)配置的。
