### ISSUE TITLE
Hello, how do you calculate your Params and Flops?

### ISSUE THREAD

**Issue by Zzz-zcy** [Eclipsess/CHIP_NeurIPS2021#12]
Hello, how do you calculate your Params and Flops?

**Comment by Eclipsess** [comment]
By thop

**Comment by Zzz-zcy** [comment]
> By thop

那是没有在代码运行中体现出来？需要自己去计算么？

**Comment by Zzz-zcy** [comment]
您好，还有关于特征图conv_feature_map_tensor().npy里面的数据是四维的，比如conv_feature_map_tensor(1).npy是(128, 16, 32, 32)，其中32×32是特征图大小，16是通道数目（也就是16张特征图），128代表一个batch_size中128张不同的输入。conv_feature_map_tensor().npy有275个数据文件，是因为repeat=5，取了5次batch_size为128的数据得出的四维特征图张量，所以得到（resnet56有55层的输出）55层*repeat=275个文件，我这样理解的对么？

**Comment by Eclipsess** [comment]
exactly right!
