### ISSUE TITLE
How to decide sparsity on each layer for any model?

### ISSUE THREAD

**Issue by leo811121** [Eclipsess/CHIP_NeurIPS2021#14]
First, thank you for contribution on structure pruning. 
I am impressed by this neat and efficient structure pruning method. However, I'd like to know how to decide sparsity on each layer for any model since I did not find any part mentioning this on paper and sparsity rate could make huge impact no matter on inference speed or accuracy.

Thank you.

**Comment by Eclipsess** [comment]
I appreciate your interest in our research.

Regarding your question, I just wanted to confirm that the sparsity in our work follows the configuration outlined in [HRankPlus](https://github.com/lmbxmu/HRankPlus).
