### ISSUE TITLE
Why not prun the model directly using the predesigned desired number of filters in each layer? 

### ISSUE THREAD

**Issue by CeliaYin0510** [Eclipsess/CHIP_NeurIPS2021#2]
Thanks for your work. I am confused about the desired number of filters to be preserved k in Algorithm 1. If k is predesigned, why not prun the model directly. Is there any advantages to pruning the model with more computation about nuclear norm?

**Comment by Eclipsess** [comment]
k is only the number of filters, but which filter should be pruned is not determined. 
The pipeline is: get a pre-trained model --> sort filters according to their importance --> preserve k most important filters --> retrain.
