### ISSUE TITLE
Issues on calculate_ci.py

### ISSUE THREAD

**Issue by zsureuk** [Eclipsess/CHIP_NeurIPS2021#3]
作者您好：

首先非常感谢您能分享这么棒的工作。

我在运行calculate_feature_maps.py的时候遇到cifar10的train_loader不能进行有效遍历（多余的参数位置，即不能for batch_idx, (inputs, targets) in enumerate(train_loader):），这个bugs我用了自己的cifar train_loader以修正。

我在运行calculate_ci.py的时候遇到以下错误：
  File "calculate_ci.py", line 22, in ci_score
    conv_output = np.round(np.load(path_conv), 4)
  File "/home/warwick/anaconda3/lib/python3.7/site-packages/numpy/lib/npyio.py", line 428, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: './feature_conv/resnet_56_repeat5/feature_convtensor(1).npy'

原因是找不到59行的path_conv = "./feature_conv/resnet_56_repeat5/feature_convtensor({0}).npy".format(str(index))
而且第60行的path_nuc = "./feature_conv_nuc/resnet_56_repeat5/feature_conv_nuctensor({0}).npy".format(str(index))
以及parser.add_argument('--feature_map_dir',type=str,default='./conv_feature_map',help='feature maps dir')都没有用到。

请问代码是不是漏掉了中间环节。
期待您的回复
谢谢

**Comment by Eclipsess** [comment]
不好意思回复晚了。由于最近事情比较多，整体代码没有完成最终的修改（之前跑实验的代码和结构太乱了QAQ）。等我最近忙完，第一时间上传整理好的代码。

**Comment by zsureuk** [comment]
感谢你能在百忙之中回复。
请问能否分享一下ImageNet的训练参数呢？比如sparsity这些。

期待您的回复
谢谢

**Comment by Eclipsess** [comment]
哈哈谢谢关注！sparsity已放在appendix上。我会随代码给出其他训练参数。

**Comment by zsureuk** [comment]
感谢您的回复。
请问ImageNet上的CI计算是跟cifar上的CI计算共享一个calculate_ci.py文件吗？
我在cifar10上用的OK，但是用这个文件计算出来的CI值用在prune_finetune_imagenet.py跑就会报错。

01/06 02:49:44 PM | Params: 16253228.00
01/06 02:49:44 PM | Flops: 2230558484.00
01/06 02:49:44 PM | resuming from pretrain model
01/06 02:49:45 PM | loading ci from: CIresnet_50/ci_conv2.npy
01/06 02:49:45 PM | loading ci from: CIresnet_50/ci_conv3.npy
01/06 02:49:45 PM | loading ci from: CIresnet_50/ci_conv4.npy
01/06 02:49:45 PM | loading ci from: CIresnet_50/ci_conv5.npy
01/06 02:49:45 PM | loading ci from: CIresnet_50/ci_conv6.npy
01/06 02:49:45 PM | loading ci from: CIresnet_50/ci_conv7.npy
Traceback (most recent call last):
  File "prune_finetune_imagenet.py", line 468, in <module>
    main()
  File "prune_finetune_imagenet.py", line 344, in main
    load_resnet_model(model, oristate_dict)
  File "prune_finetune_imagenet.py", line 149, in load_resnet_model
    state_dict[name_base+conv_weight_name][index_i][index_j] = oristate_dict[conv_weight_name][i][j]
IndexError: index 39 is out of bounds for dimension 0 with size 39
就是维度不匹配的问题

期待您的回复
谢谢

**Comment by Eclipsess** [comment]
拖延症晚期。。 不拖了。。 48h之内。。

**Comment by zsureuk** [comment]
感谢您的更新，请问可否如Hrank一样上传训练好的ImageNet的model和log呢

新年快乐
期待您的回复
谢谢

**Comment by Eclipsess** [comment]
不好意思回复晚了，已添加。迟到的2022新年快乐或者提前祝您2023年新年快乐，嘿嘿😁！
