### ISSUE TITLE
How long does it take to run python calculate_ci.py for imagenet?

### ISSUE THREAD

**Issue by Jhongn** [Eclipsess/CHIP_NeurIPS2021#5]
Hi, thank you for sharing the excellent method!
I noticed python calculate_ci.py is running on CPU, not GPU.
It took me very little time to run this program for cifar but a long time for imagenet.
How long does it take to run python calculate_ci.py for imagenet?

**Comment by Eclipsess** [comment]
It indeed takes a long time to calculate CI for imagenet. 
You can set a flag (i.e., print something after calculating one layer?) to monitor the progress.
