### ISSUE TITLE
weight decay question

### ISSUE THREAD

**Issue by geyao-c** [Eclipsess/CHIP_NeurIPS2021#7]
原论文中resnet56在cifar10上的微调的weight decay 为0.05，请问是不是笔误了呢，实际上应该是0.005.
<img width="749" alt="image" src="https://user-images.githubusercontent.com/45726681/166481113-5bc1d5bc-55cf-48a1-aaf3-ff8e11b9ccdc.png">

**Comment by Eclipsess** [comment]
是的，应该是0.005，感谢指正。
