### ISSUE TITLE
reproduce accuracy

### ISSUE THREAD

**Issue by geyao-c** [Eclipsess/CHIP_NeurIPS2021#8]
您好，请问resnet56在cifar10上裁剪大约43%的参数后，是多次结果取最高值吗。在您最新给出的微调参数下我运行3次后得到的结果分别是93.99，93.64，93.78，没有达到论文汇总94.16的效果。这是实验日志https://drive.google.com/drive/folders/1v4UNqc7AwDNy-y36U2KOtbHYPO8c_P2w?usp=sharing。当使用论文中给出的微调参数，lr=0.01、epoch=300、weight decay=0.005、momentum=0.9、lr type=cos、label smooth=0.0，运行四次的结果分别是93.9，93.97，94.01，93.94。请问是参数设置是有误差，还是实验结果要多运行几次去最高值呢？非常感谢。

**Comment by Eclipsess** [comment]
感谢对CHIP的关注。
“是多次结果取最高值吗”: 是的。compression大多数paper都会取最高值比较。
“参数设置是有误差, 还是实验结果要多运行几次去最高值呢”: 可以参考在README中放出的参数设置和训练log，重复运行几次: [link](https://drive.google.com/drive/folders/1r7eb1QPmsJlYNmDvAL-V68SGGV0XHP6p)，大概率会得到比paper中更好的结果。
