### ISSUE TITLE
Code on MobileNet

### ISSUE THREAD

**Issue by sscckk** [Eclipsess/CHIP_NeurIPS2021#9]
您好，请问您在MobileNet之类的新型网络中测试过该方法吗？如MobileNetV2，效果如何呢？

**Comment by JuttaZhang** [comment]
可以看一下作者的rebuttal，有提到

**Comment by sscckk** [comment]
谢谢，找到了rebuttal中的结果。不过还有一个疑问，就是MobileNetV2的分层剪枝率如何设置呢，因为MobileNetV2中存在group conv，这和ResNet等其他模型存在明显差别。

**Comment by JuttaZhang** [comment]
这个你可以参考一下HRank的源码
